name: Telegram Bot CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install python-telegram-bot opencv-python

      - name: Debugging Step
        run: |
          echo -e "\n\033[1;34mCurrent Directory: \033[0m$(pwd)"
          echo -e "\n\033[1;34mContents of the Directory: \033[0m$(ls -la)"
          echo -e "\n\033[1;34mTELEGRAM_BOT_TOKEN: \033[0m${{ secrets.TELEGRAM_BOT_TOKEN }}"
          chmod +x pixelateTG.py
          echo -e "\n\033[1;34mScript Permissions: \033[0m$(ls -la pixelateTG.py)"
          # Add more debug statements as needed

      - name: Run bot
        run: python pixelateTG.py ${{ secrets.TELEGRAM_BOT_TOKEN }}
