name: Telegram Bot CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-telegram-bot opencv-python

      - name: Debugging Step
        run: |
          echo "Current Directory: $(pwd)"
          echo "Contents of the Directory: $(ls -la)"
          echo "TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}"
          chmod +x pixelateTG.py
          echo "Script Permissions: $(ls -la pixelateTG.py)"
          # Add more debug statements as needed

      - name: Run bot
        run: python pixelateTG.py ${{ secrets.TELEGRAM_BOT_TOKEN }}
