name: Pixelbot

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set Telegram BOT token
        run: echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> $GITHUB_ENV

      - name: Run Prettier
        run: npm install --global prettier
          
      - name: Format code with Prettier
        run: prettier --write .

      - name: Run bot
        run: |
          python pixelateTG.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}

